apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: websocket-gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: websocket-gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http