apiVersion: v1
kind: Secret
metadata:
  name: listmonk-secrets
  namespace: listmonk
type: Opaque
stringData:
  SERVICEBUS_CONNECTION_STRING: "$SB_CONN"
  LISTMONK_db__password: "$DB_PASSWORD"
  password: "$DB_PASSWORD"
