apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: listmonk-proxy
  namespace: listmonk
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: listmonk
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
