helmDefaults:
  createNamespace: true
  atomic: true
  wait: true
  timeout: 600
  cleanupOnFail: true

environments:
  azure:
    values:
      - env.yaml

helmfiles:
  - ../../../releases/listmonk.yaml.gotmpl
  - ../../../releases/prometheus.yaml.gotmpl
  - ../../../releases/frontend.yaml.gotmpl
