service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /ping

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesGateway:
    enabled: true

# Disable chart-managed Gateway; we create our own in manifests/traefik/gateway.yaml
gateway:
  enabled: false

ports:
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
