controllers:
  main:
    replicas: 1
    containers:
      main:
        image:
          repository: proiectpcdproductionacr.azurecr.io/websocket-gateway
          tag: latest
          pullPolicy: Always
        env:
          PORT: "8080"
          COSMOS_ENDPOINT: ""
          COSMOS_KEY: ""
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        probes:
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 10

service:
  main:
    controller: main
    ports:
      http:
        port: 8080
        protocol: HTTP
