apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-proiectpcd-online
  namespace: traefik
spec:
  secretName: wildcard-proiectpcd-online-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "proiectpcd.online"
    - "*.proiectpcd.online"
